### ISSUE TITLE
Trying to sync any repository URL returns a 404

### ISSUE THREAD

**Issue by mattiascockburn** [ATIX-AG/foreman_scc_manager#43] opened 2020-08-26 15:20 UTC
Heya,

first of all thank you very much for this effort, i was delighted to see this level of integration between the SUSE Customer Center and Katello. Unfortunately i encountered an issue right away while getting my feet wet with this plugin:

I could add my organization credentials without issue, sync products from SCC and later enable them. (for example `SUSE Linux Enterprise Server 12 SP5 x86_64`). `foreman_scc_manager` then created the respective product and associated repositories just fine. But when i then try to sync a given repository (like `1878 SUSE Linux Enterprise Server 12 SP5 x86_64 SLES12-SP5-Pool for sle-12-x86_64` in my case) the underlying task fails:

```
{"pulp_tasks"=>
  [{"pulp_href"=>"/pulp/api/v3/tasks/2efada73-33c8-4c51-ba9e-6385514b2e63/",
    "pulp_created"=>"2020-08-26T15:18:04.694+00:00",
    "state"=>"failed",
    "name"=>"pulp_rpm.app.tasks.synchronizing.synchronize",
    "started_at"=>"2020-08-26T15:18:04.791+00:00",
    "finished_at"=>"2020-08-26T15:18:04.915+00:00",
    "error"=>
     {"traceback"=>
       "  File \"/usr/lib/python3.6/site-packages/rq/worker.py\", line 883, in perform_job\n" +
       "    rv = job.perform()\n" +
       "  File \"/usr/lib/python3.6/site-packages/rq/job.py\", line 645, in perform\n" +
       "    self._result = self._execute()\n" +
       "  File \"/usr/lib/python3.6/site-packages/rq/job.py\", line 651, in _execute\n" +
       "    return self.func(*self.args, **self.kwargs)\n" +
       "  File \"/usr/lib/python3.6/site-packages/pulp_rpm/app/tasks/synchronizing.py\", line 162, in synchronize\n" +
       "    remote_url = fetch_remote_url(remote)\n" +
       "  File \"/usr/lib/python3.6/site-packages/pulp_rpm/app/tasks/synchronizing.py\", line 130, in fetch_remote_url\n" +
       "    return fetch_mirror(remote)\n" +
       "  File \"/usr/lib/python3.6/site-packages/pulp_rpm/app/tasks/synchronizing.py\", line 111, in fetch_mirror\n" +
       "    result = downloader.fetch()\n" +
       "  File \"/usr/lib/python3.6/site-packages/pulpcore/download/base.py\", line 160, in fetch\n" +
       "    return done.pop().result()\n" +
       "  File \"/usr/lib/python3.6/site-packages/pulpcore/download/base.py\", line 227, in run\n" +
       "    return await self._run(extra_data=extra_data)\n" +
       "  File \"/usr/lib/python3.6/site-packages/pulp_rpm/app/downloaders.py\", line 43, in _run\n" +
       "    response.raise_for_status()\n" +
       "  File \"/usr/lib64/python3.6/site-packages/aiohttp/client_reqrep.py\", line 946, in raise_for_status\n" +
       "    headers=self.headers)\n",
      "description"=>
       "404, message='Not Found', url=URL('https://updates.suse.com/SUSE/Products/SLE-SERVER/12-SP5/x86_64/product/?A_VERY_LONG_TOKEN')"},
    "worker"=>"/pulp/api/v3/workers/bd448edc-5907-4416-92ee-9ee507d7d809/",
    "child_tasks"=>[],
    "progress_reports"=>[],
    "created_resources"=>[],
    "reserved_resources_record"=>
     ["/pulp/api/v3/repositories/rpm/rpm/9b288ce3-0929-4c60-8479-488dbdf26856/",
      "/pulp/api/v3/remotes/rpm/rpm/82d2d5d8-07bc-4aff-bc53-1298150186fa/"]}],
 "create_version"=>true,
 "task_groups"=>[],
 "poll_attempts"=>{"total"=>1, "failed"=>1}}
```

And well, i receive a 404 as well when i try to visit the specific repository URL. Any hints on how to troubleshoot further?

Thanks and regards,

Mattas

**Comment by quba42** [comment] 2020-08-26 15:37
May I still ask what base OS, version of Foreman/Katello, and what version of `tfm-rubygem-foreman_scc_manager` you have installed?
(I have not yet looked at your issue in detail, but this is almost always useful information).

**Comment by mattiasgiese** [comment] 2020-08-26 16:06
> May I still ask what base OS, version of Foreman/Katello, and what version of `tfm-rubygem-foreman_scc_manager` you have installed?
> (I have not yet looked at your issue in detail, but this is almost always useful information).

Of course, silly me. Here goes:

```
[root@katello ~]# rpm -q katello foreman tfm-rubygem-foreman_scc_manager
katello-3.16.0-1.el7.noarch
foreman-2.1.2-1.el7.noarch
tfm-rubygem-foreman_scc_manager-1.8.4-1.fm2_1.el7.noarch
[root@katello ~]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
```

**Comment by jtruestedt** [comment] 2020-08-27 05:35
Is your foreman connecting directly to the internet or using an http-proxy?
Are you already using the new pulp3 for the rpm-Repositories?

**Comment by quba42** [comment] 2020-08-27 07:18
I can see from the traceback, that this is indeed pulp3.

The truth is that we (the plugin maintainers) are internally still working mostly on pulp2.
It is possible there is some incompatibility between the SCC manager and pulp3 that we have simply not noticed yet.

@m-bucher might have some ideas how to proceed with this issue once he is back from holidays on Monday.

**Comment by mattiasgiese** [comment] 2020-08-28 16:45
> Is your foreman connected directly to the internet or using an http-proxy?
> Are you already using the new pulp3 for the rpm-Repositories?

This system in particular is directly connected to the internet and is using pulp3

**Comment by m-bucher** [comment] 2020-09-01 14:38
Looks like the Token is not correctly transmitted to pulpcore.
In difference to pulp2, pulpcore requires the Token to be specified as a separate parameter and not as part of the URL.

This might have to be fixed in katello, I opened a TIcket for it: https://projects.theforeman.org/issues/30752

**Comment by mattiasgiese** [comment] 2020-09-01 15:27
> Looks like the Token is not correctly transmitted to pulpcore.
> In difference to pulp2, pulpcore requires the Token to be specified as a separate parameter and not as part of the URL.
> 
> This might have to be fixed in katello, I opened a TIcket for it: https://projects.theforeman.org/issues/30752

Thank you very much for your reply. I will follow this issue closely. Due to time restrictions i had to downgrade to Katello 3.15 for this particular project but will keep a current Katello 3.16.1/Dev running in order to test this out.

**Comment by quba42** [comment] 2020-09-08 10:39
Looks like there is now an upstream PR for the issue opened by @m-bucher:
https://github.com/Katello/katello/pull/8928

**Comment by quba42** [comment] 2020-09-08 11:16
I should add that this fix is slated for inclusion in Katello version `3.17`.

**Comment by laugmanuel** [comment] 2021-08-18 06:50
I do hit the same issue. Sync worked fine in Pulp2, then after migration to Pulp3, I only get 404 errors for all the Suse repositories.
Are there steps needed to fix/migrate the repo URL after Pulp2-to-3-Migration?

**Comment by m-bucher** [comment] 2021-08-18 19:52
@laugmanuel looks like this is a problem with the pulp-2to3-migrations, so you might want to open a ticket there as well.

You may be able to manually fix it by going to the Katello-repository, edit the URL and save it again. I think this should trigger an update to pulpcore from katello. Katello should send the token as a separate option to pulpcore.

**Comment by laugmanuel** [comment] 2021-08-18 19:55
@m-bucher I've managed to fix all our repos by switching the download policy back and fourth.
Now, the Pulp API shows the sles_auth_token populated correctly.
I will open an issue over there as well.

**Comment by laugmanuel** [comment] 2021-08-19 06:31
I've created an upstream issue here: https://pulp.plan.io/issues/9254
In the end, I can confirm that the PR (https://github.com/Katello/katello/pull/8928) fixes this issue here.

**Comment by nadjaheitmann** [comment] 2022-02-16 13:01
Looks like this has been solved some time ago.

**Closed** 2022-02-16 13:01 UTC
