### ISSUE TITLE
undefined method `katello_gpg_key_id' for #<SccAccount:0x00007fe7a34f3020>

### ISSUE THREAD

**Issue by ezr-ondrej** [ATIX-AG/foreman_scc_manager#88] opened 2022-01-24 15:32 UTC
https://projects.theforeman.org/issues/34241

**Comment by nadjaheitmann** [comment] 2022-01-24 17:35
Should be fixed by #79 and #87. I cannot reproduce it on Foreman 3.1, anymore.

**Comment by SGetovski** [comment] 2022-01-27 06:15
Here is the update, coming from the Foreman Bug #34241 that I have opened, given by Andrew Dewar:

_We've updated most of our gpg key logic in katello, this issue should likely be brought up in the scc-manager plugin repo here: https://github.com/ATIX-AG/foreman_scc_manager.

I suspect that the scc-manager plugin requires an update to their API call.

If they can confirm a that a specific api is still producing these kinds of errors, do please come back here and we'll be happy to address the issue.

Cheers_

**Closed** 2022-02-16 11:18 UTC
