### ISSUE TITLE
Undefined method epoch_to_date when syncing

### ISSUE THREAD

**Issue by dgoetz** [ATIX-AG/foreman_scc_manager#93] opened 2022-04-06 12:49 UTC
I followed the suggestion in https://community.theforeman.org/t/scc-plugin-issues-after-update-to-katello-4-3/27346/ to get sync running again and now one step forward the sync is running with warning showing the following error message:
```
undefined method `epoch_to_date' for Katello::Pulp3::Erratum:Class
```

Except from this it looks like the sync worked fine. 
Repository was "SUSE Linux Enterprise Server 15 SP1 s390x".

**Comment by nadjaheitmann** [comment] 2022-04-06 13:21
Thanks for reporting @dgoetz Which Katello version are you at?

**Comment by dgoetz** [comment] 2022-04-06 13:41
The environment was updated to Katello 4.4 on monday.

**Comment by nadjaheitmann** [comment] 2022-04-07 08:09
Thanks. Do you mind providing a backtrace? It is a bit unclear what exactly is causing the warning. Does it work for non-SUSE repositories without warning?

**Comment by dgoetz** [comment] 2022-04-07 09:49
Is this part of the Foreman production.log enough?

```
# grep 9ceef41d /var/log/foreman/production.log
2022-04-07T11:32:42 [I|app|9ceef41d] Started POST "/katello/api/v2/repositories/1916/sync?organization_id=1" for 10.2.225.145 at 2022-04-07 11:32:42 +0200
2022-04-07T11:32:42 [I|app|9ceef41d] Processing by Katello::Api::V2::RepositoriesController#sync as HTML
2022-04-07T11:32:42 [I|app|9ceef41d]   Parameters: {"id"=>"1916", "organization_id"=>"1", "api_version"=>"v2", "repository"=>{"id"=>"1916"}}
2022-04-07T11:32:42 [I|bac|9ceef41d] Task {label: , execution_plan_id: 82974cec-71b2-4ad8-9491-e0b9288775d9} state changed: pending 
2022-04-07T11:32:42 [I|bac|9ceef41d] Task {label: Actions::Katello::Repository::Sync, id: b1d7ffb4-a7e7-4715-bb3c-c6a544243b7c, execution_plan_id: 82974cec-71b2-4ad8-9491-e0b9288775d9} state changed: planning 
2022-04-07T11:32:42 [I|bac|9ceef41d] Task {label: Actions::Katello::Repository::Sync, id: b1d7ffb4-a7e7-4715-bb3c-c6a544243b7c, execution_plan_id: 82974cec-71b2-4ad8-9491-e0b9288775d9} state changed: planned 
2022-04-07T11:32:42 [I|app|9ceef41d]   Rendering /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/views/katello/api/v2/repositories/sync.json.rabl within katello/api/v2/layouts/resource
2022-04-07T11:32:42 [I|app|9ceef41d]   Rendered /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/views/katello/api/v2/repositories/sync.json.rabl within katello/api/v2/layouts/resource (Duration: 31.8ms | Allocations: 22798)
2022-04-07T11:32:42 [I|app|9ceef41d] Completed 202 Accepted in 449ms (Views: 35.3ms | ActiveRecord: 23.8ms | Allocations: 134261)
2022-04-07T11:32:42 [I|bac|9ceef41d] Task {label: Actions::Katello::Repository::Sync, id: b1d7ffb4-a7e7-4715-bb3c-c6a544243b7c, execution_plan_id: 82974cec-71b2-4ad8-9491-e0b9288775d9} state changed: running 
2022-04-07T11:32:45 [I|app|9ceef41d] CONTENT_INDEX type=Katello::Rpm success=true duration=342.7
2022-04-07T11:32:45 [I|app|9ceef41d] CONTENT_INDEX type=Katello::ModuleStream success=true duration=59.58
2022-04-07T11:32:45 [I|app|9ceef41d] CONTENT_INDEX type=Katello::Erratum success=false duration=238.06
2022-04-07T11:32:45 [E|bac|9ceef41d] undefined method `epoch_to_date' for Katello::Pulp3::Erratum:Class (NoMethodError)
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/pulp3/erratum.rb:119:in `convert_date_if_epoch'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/pulp3/erratum.rb:37:in `generate_model_row'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/content_unit_indexer.rb:38:in `block (2 levels) in import_all'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/content_unit_indexer.rb:34:in `map'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/content_unit_indexer.rb:34:in `block in import_all'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/pulp3/pulp_content_unit.rb:97:in `yield'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/pulp3/pulp_content_unit.rb:97:in `block (2 levels) in pulp_units_batch_for_repo'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/pulp3/pulp_content_unit.rb:85:in `loop'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/pulp3/pulp_content_unit.rb:85:in `block in pulp_units_batch_for_repo'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/content_unit_indexer.rb:27:in `each'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/services/katello/content_unit_indexer.rb:27:in `import_all'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/models/katello/repository.rb:918:in `block (2 levels) in index_content'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/lib/katello/logging.rb:8:in `time'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/models/katello/repository.rb:917:in `block in index_content'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/models/katello/repository.rb:916:in `each'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/models/katello/repository.rb:916:in `index_content'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-4.4.0/app/lib/actions/katello/repository/index_content.rb:22:in `run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:582:in `block (3 levels) in execute_run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:19:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/rails_executor_wrap.rb:14:in `block in run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/execution_wrapper.rb:88:in `wrap'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/rails_executor_wrap.rb:13:in `run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:23:in `call'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:19:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action/progress.rb:31:in `with_progress_calculation'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action/progress.rb:17:in `run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:23:in `call'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:19:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/load_setting_values.rb:20:in `run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:23:in `call'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:19:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_request_id.rb:15:in `block in run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_request_id.rb:52:in `restore_current_request_id'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_request_id.rb:15:in `run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:23:in `call'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:19:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_timezone.rb:15:in `block in run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_timezone.rb:44:in `restore_curent_timezone'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_timezone.rb:15:in `run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:23:in `call'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:19:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `block in run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_taxonomies.rb:45:in `restore_current_taxonomies'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:23:in `call'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:19:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:32:in `run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:23:in `call'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:27:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware.rb:19:in `pass'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_user.rb:15:in `block in run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_user.rb:54:in `restore_curent_user'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-6.0.0/app/lib/actions/middleware/keep_current_user.rb:15:in `run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/stack.rb:23:in `call'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/middleware/world.rb:31:in `execute'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:581:in `block (2 levels) in execute_run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:580:in `catch'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:580:in `block in execute_run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:483:in `block in with_error_handling'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:483:in `catch'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:483:in `with_error_handling'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:575:in `execute_run'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/action.rb:296:in `execute'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:18:in `block (2 levels) in execute'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/execution_plan/steps/abstract.rb:167:in `with_meta_calculation'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:17:in `block in execute'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:32:in `open_action'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:16:in `execute'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/director.rb:69:in `execute'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/executors/sidekiq/worker_jobs.rb:11:in `block (2 levels) in perform'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/executors.rb:18:in `run_user_code'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/executors/sidekiq/worker_jobs.rb:9:in `block in perform'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/executors/sidekiq/worker_jobs.rb:25:in `with_telemetry'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/executors/sidekiq/worker_jobs.rb:8:in `perform'
 9ceef41d | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/executors/sidekiq/serialization.rb:27:in `perform'
 9ceef41d | [ sidekiq ]
 9ceef41d | [ concurrent-ruby ]
2022-04-07T11:32:46 [I|bac|9ceef41d] Task {label: Actions::Katello::Repository::Sync, id: b1d7ffb4-a7e7-4715-bb3c-c6a544243b7c, execution_plan_id: 82974cec-71b2-4ad8-9491-e0b9288775d9} state changed: stopped  result: warning
```

And I mixed up product and repository yesterday. It is repository 'SLE15-SP1-Installer-Updates for sle-15-s390x' and product 'SUSE Linux Enterprise Server 15 SP1 s390x'.

Other repositories are RHEL, Amazon Linux and some custom ones and no warning there, but it could of course still be an issue for a different part of the software stack.

**Comment by nadjaheitmann** [comment] 2022-04-07 09:58
Yeah, that helps, thanks! Looks like a bug in Katello on the first glance. I suppose that the other repos do not use epoch and that is why there is no warning during the sync. I suppose that this commit https://github.com/Katello/katello/commit/215b0401dcdda07ecf300d1751b43c2062f461e3 broke the syncing. Might be a `self` missing in here: https://github.com/Katello/katello/blame/master/app/services/katello/pulp3/erratum.rb#L122

**Comment by nadjaheitmann** [comment] 2022-05-11 08:40
The issue is fixed in https://github.com/Katello/katello/pull/10081 and will hopefully be cherry-picked to 4.4 https://github.com/Katello/katello/pull/10103

**Closed by nadjaheitmann** 2022-05-11 08:41 UTC
